import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#9ec9f5",
        "muted-border": "#E8D5D6",
        "on-background": "#1b1c1a",
        "outline": "#6f787d",
        "primary-fixed": "#d6e8fb",
        "secondary-fixed": "#ffdede",
        "sage-haze": "#F2E4E5",
        "tertiary-fixed-dim": "#7eff91",
        "on-primary-fixed": "#001f29",
        "inverse-primary": "#9ec9f5",
        "on-tertiary-container": "#00390a",
        "on-tertiary-fixed-variant": "#005312",
        "surface-dim": "#E4CDCE",
        "outline-variant": "#bec8cd",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#40000d",
        "surface-container": "#F1E3E3",
        "on-surface": "#1b1c1a",
        "ink-charcoal": "#1A1D21",
        "surface-bright": "#FAF4F4",
        "on-tertiary": "#ffffff",
        "tertiary": "#18a12d",
        "accent": "#3bff55",
        "accent-container": "#25d83d",
        "secondary-container": "#e84444",
        "surface-container-low": "#F6ECEC",
        "on-primary-container": "#d6e8fb",
        "on-primary-fixed-variant": "#0e4b85",
        "primary": "#277dce",
        "on-tertiary-fixed": "#002205",
        "secondary-fixed-dim": "#ffa6a6",
        "secondary": "#ff5c5c",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#3bff55",
        "on-secondary-fixed-variant": "#850f0f",
        "primary-container": "#1c66ad",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-tint": "#277dce",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#E4CDCE",
        "background": "#fafafa",
        "inverse-surface": "#2f312e",
        "surface-variant": "#E4CDCE",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f1ed",
        "error-container": "#ffdad6",
        "on-surface-variant": "#3f484c",
        "surface": "#fafafa",
        "tertiary-fixed": "#3bff55",
        "surface-container-high": "#EBD8D9",
        "surface-container-lowest": "#ffffff",
        "paper-cream": "#fafafa",
        // Legacy brand colors preserved for backward compatibility
        brand: {
          blue: {
            50: "#F0F7FB",
            100: "#E2F0F8",
            200: "#C5E1F2",
            300: "#98C9E7",
            400: "#64ACD8",
            500: "#3E8EC5",
            600: "#2B72A6",
            700: "#245C86",
            800: "#224D6F",
            900: "#20425C",
            950: "#152B3C",
          },
          pink: {
            50: "#FDF2F4",
            100: "#FCE5E9",
            200: "#F9CFD7",
            300: "#F4ABB8",
            400: "#EB798F",
            500: "#DD516E",
            600: "#C86458",
            700: "#AB2C4A",
            800: "#8E2740",
            900: "#79253B",
            950: "#440F1D",
          },
          teal: {
            DEFAULT: "#2C4653",
            600: "#2C4653",
            700: "#223843",
          },
          coral: {
            DEFAULT: "#C86458",
            500: "#C86458",
            600: "#B44C40",
          }
        },
        ink: {
          DEFAULT: "#0F172A",
          muted: "#475569",
          subtle: "#64748B",
          border: "#E2E8F0",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "4px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "headline-lg": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "label-sm": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "quote-text": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "body-lg": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "display-xl": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "title-md": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "body-md": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        sans: ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "quote-text": ["20px", { lineHeight: "30px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        flat: "2px 2px 0px 0px rgba(15, 23, 42, 1)",
        'flat-blue': "2px 2px 0px 0px rgba(62, 142, 197, 1)",
        'flat-pink': "2px 2px 0px 0px rgba(200, 100, 88, 1)",
        subtle: "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
