import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#93c5fd",
        "muted-border": "#e2e8f0",
        "on-background": "#0f172a",
        "outline": "#64748b",
        "primary-fixed": "#dbeafe",
        "secondary-fixed": "#ffe4e6",
        "sage-haze": "#f0f7ff",
        "tertiary-fixed-dim": "#86efac",
        "on-primary-fixed": "#0f172a",
        "inverse-primary": "#93c5fd",
        "on-tertiary-container": "#064e3b",
        "on-tertiary-fixed-variant": "#047857",
        "surface-dim": "#e2e8f0",
        "outline-variant": "#cbd5e1",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#881337",
        "surface-container": "#f8fafc",
        "on-surface": "#0f172a",
        "ink-charcoal": "#0f172a",
        "surface-bright": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary": "#10b981",
        "accent": "#10b981",
        "accent-container": "#34d399",
        "secondary-container": "#e11d48",
        "surface-container-low": "#ffffff",
        "on-primary-container": "#1e3a8a",
        "on-primary-fixed-variant": "#1d4ed8",
        "primary": "#2563eb",
        "on-tertiary-fixed": "#064e3b",
        "secondary-fixed-dim": "#fecdd3",
        "secondary": "#f43f5e",
        "on-secondary-container": "#ffffff",
        "tertiary-container": "#10b981",
        "on-secondary-fixed-variant": "#be123c",
        "primary-container": "#1d4ed8",
        "error": "#ef4444",
        "on-error-container": "#7f1d1d",
        "surface-tint": "#2563eb",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e8f0",
        "background": "#ffffff",
        "inverse-surface": "#1e293b",
        "surface-variant": "#f1f5f9",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f8fafc",
        "error-container": "#fee2e2",
        "on-surface-variant": "#475569",
        "surface": "#ffffff",
        "tertiary-fixed": "#10b981",
        "surface-container-high": "#f1f5f9",
        "surface-container-lowest": "#ffffff",
        "paper-cream": "#ffffff",
        // Legacy brand colors preserved for backward compatibility
        brand: {
          blue: {
            50: "#F0F7FB",
            100: "#E2F0F8",
            200: "#C5E1F2",
            300: "#98C9E7",
            400: "#64ACD8",
            500: "#3E8EC5",
            600: "#2B72A6",
            700: "#245C86",
            800: "#224D6F",
            900: "#20425C",
            950: "#152B3C",
          },
          pink: {
            50: "#FDF2F4",
            100: "#FCE5E9",
            200: "#F9CFD7",
            300: "#F4ABB8",
            400: "#EB798F",
            500: "#DD516E",
            600: "#C86458",
            700: "#AB2C4A",
            800: "#8E2740",
            900: "#79253B",
            950: "#440F1D",
          },
          teal: {
            DEFAULT: "#2C4653",
            600: "#2C4653",
            700: "#223843",
          },
          coral: {
            DEFAULT: "#C86458",
            500: "#C86458",
            600: "#B44C40",
          }
        },
        ink: {
          DEFAULT: "#0F172A",
          muted: "#475569",
          subtle: "#64748B",
          border: "#E2E8F0",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "4px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "headline-lg": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "label-sm": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "quote-text": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "body-lg": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "display-xl": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "title-md": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        "body-md": ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        sans: ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['"Inter Display"', '"Inter Display Placeholder"', 'Inter', 'sans-serif'],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "quote-text": ["20px", { lineHeight: "30px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      boxShadow: {
        flat: "2px 2px 0px 0px rgba(15, 23, 42, 1)",
        'flat-blue': "2px 2px 0px 0px rgba(62, 142, 197, 1)",
        'flat-pink': "2px 2px 0px 0px rgba(200, 100, 88, 1)",
        subtle: "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
